### PR TITLE
Various Grammatical and Spelling Changes

### PR DESCRIPTION
**Pull request by analytalica**
I've corrected some grammar and spelling issues, primarily relating to possessive vs. plural spellings.

While this repo doesn't appear fully updated (for example, it lacks the combat simulator text boxes, I was hoping to improve the writing quality of FTL CE and I stumbled upon this repo through Google. Any chance the latest version of FTL CE could be put on GitHub?

### CODE REVIEW

**Comment by sleeper-service-CE** [comment]
Yeah this repo is years old and not up to date any more. I'm not a git hub expert and I'm curious how it is still visible to you... Probably cause kartoFlane made it and I have no writing permission for it, so I have no way to delete it.

Anyway... I'm happy that you would event consider spellchecking CE, your help would be most appreciated!
The mod has grown quite a bit and there are large parts (for example the events in the latest new sector types) that have never been checked. A complete check would take quite a while I think, but it's up to you how much time you want to invest in this. I created a new Repo:
https://github.com/sleeper-service-CE/FTL-Captain-s-Edition-Spellchecking-2015.git
But I wasn't successful in committing my files. I have no real Idea how to do this and didn't get any further using guides... Well after following this guide
http://lifehacker.com/5983680/how-the-heck-do-i-use-github
I finally got this...

 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/sleeper-service-CE/FTL-Captain-s-Edition-Spellchecking-2015.git'
To prevent you from losing history, non-fast-forward updates were rejected
Merge the remote changes (e.g. 'git pull') before pushing again.  See the
'Note about fast-forwards' section of 'git push --help' for details.
sleeper@Hal:~/Desktop/FTL_Modding/FTL Captains Edition/Final/data$ 

So yeah, If I can get this to work then you help would be most appreciated... I give up for now. I don't know if you can commit the current files to the repository yourself, basically everything thats in /data/ and starts with events_ needs checking, as well as blueprints.xml.append...

Thanks so far
Stefan




--------------------------------------------
analytalica <notifications@github.com> schrieb am So, 4.1.2015:

 Betreff: [CE-1.07-spell-check] Various Grammatical and Spelling Changes (#1)
 An: "kartoFlane/CE-1.07-spell-check" <CE-1.07-spell-check@noreply.github.com>
 Datum: Sonntag, 4. Januar, 2015 06:57 Uhr
 
 I've corrected some grammar
 and spelling issues, primarily relating to possessive vs.
 plural spellings.
 
 While this repo doesn't appear fully updated (for
 example, it lacks the combat simulator text boxes, I was
 hoping to improve the writing quality of FTL CE and I
 stumbled upon this repo through Google. Any chance the
 latest version of FTL CE could be put on GitHub?
 
 
 
 You can merge this Pull Request by running
   git pull
 https://github.com/analytalica/CE-1.07-spell-check
 master
 Or view, comment on, or merge it at:
   https://github.com/kartoFlane/CE-1.07-spell-check/pull/1
 
 Commit Summary
 
   Fixed some minor typos and grammatical error(s).
   Corrected some 'stations' to
 'station's'
 
 
 File Changes
 
   
     M
     README.md
     (2)
   
   
     M
     events.xml.append
     (40)
   
   
     M
     events_fuel.xml.append
     (4)
   
   
     M
     events_nebula.xml.append
     (12)
   
   
     M
     events_pirate.xml.append
     (10)
   
   
     M
     events_rebel.xml.append
     (4)
   
   
     M
     events_slug.xml.append
     (8)
   
 
 
 Patch Links:
 
   https://github.com/kartoFlane/CE-1.07-spell-check/pull/1.patch
   https://github.com/kartoFlane/CE-1.07-spell-check/pull/1.diff
 
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by sleeper-service-CE** [comment]
Ah ok, I think I got it to work. The current files of 1.269 can be found in my own repo now:
https://github.com/sleeper-service-CE/FTL-Captain-s-Edition-Spellchecking-2015

Any help you can render with spell-checking would be most appreciated. I'll put you in the credits.

Stefan



--------------------------------------------
analytalica <notifications@github.com> schrieb am So, 4.1.2015:

 Betreff: [CE-1.07-spell-check] Various Grammatical and Spelling Changes (#1)
 An: "kartoFlane/CE-1.07-spell-check" <CE-1.07-spell-check@noreply.github.com>
 Datum: Sonntag, 4. Januar, 2015 06:57 Uhr
 
 I've corrected some grammar
 and spelling issues, primarily relating to possessive vs.
 plural spellings.
 
 While this repo doesn't appear fully updated (for
 example, it lacks the combat simulator text boxes, I was
 hoping to improve the writing quality of FTL CE and I
 stumbled upon this repo through Google. Any chance the
 latest version of FTL CE could be put on GitHub?
 
 
 
 You can merge this Pull Request by running
   git pull
 https://github.com/analytalica/CE-1.07-spell-check
 master
 Or view, comment on, or merge it at:
   https://github.com/kartoFlane/CE-1.07-spell-check/pull/1
 
 Commit Summary
 
   Fixed some minor typos and grammatical error(s).
   Corrected some 'stations' to
 'station's'
 
 
 File Changes
 
   
     M
     README.md
     (2)
   
   
     M
     events.xml.append
     (40)
   
   
     M
     events_fuel.xml.append
     (4)
   
   
     M
     events_nebula.xml.append
     (12)
   
   
     M
     events_pirate.xml.append
     (10)
   
   
     M
     events_rebel.xml.append
     (4)
   
   
     M
     events_slug.xml.append
     (8)
   
 
 
 Patch Links:
 
   https://github.com/kartoFlane/CE-1.07-spell-check/pull/1.patch
   https://github.com/kartoFlane/CE-1.07-spell-check/pull/1.diff
 
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by kartoFlane** [comment]
Yeah, the way GitHub works is that you can fork other people's repositories, creating your own copy that you can work on. However, it doesn't automatically sync up with the original repository (you have to do this yourself), hence this repo is *quite* stale by now.

I guess since Sleeper deleted his own repo, my fork now shows up as a standalone... Good to know that that's how it works, I guess :P
Anyhow, I'll delete this repo in a few days (if I don't forget about it, again...)

**Comment by analytalica** [comment]
OK great! I'll close this pull request and will help out on the latest repo. Thanks!

**Comment by sleeper-service-CE** [comment]
It's you we have to thank. :)

--------------------------------------------
analytalica <notifications@github.com> schrieb am So, 4.1.2015:

 Betreff: Re: [CE-1.07-spell-check] Various Grammatical and Spelling Changes (#1)
 An: "kartoFlane/CE-1.07-spell-check" <CE-1.07-spell-check@noreply.github.com>
 CC: "sleeper-service-CE" <stefan.widany@yahoo.de>
 Datum: Sonntag, 4. Januar, 2015 17:56 Uhr
 
 OK great! I'll close this
 pull request and will help out on the latest repo.
 Thanks!
 
 —
 Reply to this email directly or view
 it on GitHub.

**Pull request closed without merging**
